name: my first github action workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: hello display
        run: echo "Welcome to kk funda devops"
